/**
 * @fileoverview This is a compiled JavaScript file that serves as the entry point for the backend.
 * Genezio requires a .js file to run on its serverless infrastructure.
 * This file would be generated by your build process from your index.tsx.
 *
 * It is structured to work with Genezio's `httpServer` type, using a named handler function.
 */

// Import necessary modules, like Express.
const express = require('express');

// You would likely have other imports from your project here,
// like API routers or database connections.

// Create the Express app instance.
const app = express();
app.use(express.json());

// Set up a simple root route to check if the server is working.
app.get('/', (req, res) => {
  res.send('Hello from the backend!');
});

// Define the handler function as the entry point.
// Genezio's `httpServer` type uses this function to handle all incoming requests.
// You specified 'handler' in your genezio.yaml file, so this function name is crucial.
exports.handler = app;

/**
 * You can also define other API routes and middleware here, for example:
 * * app.post('/api/data', (req, res) => {
 * const data = req.body;
 * // Process data
 * res.status(200).json({ status: 'Data received' });
 * });
 * */
